name 'custom_haproxy'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures haproxy'
long_description 'Installs/Configures haproxy'
version '0.1.1'

depends 'haproxy', '~> 2.0.0'
depends 'sysctl', '~> 0.8.1'
